### ISSUE TITLE
"volume node affinity conflict"

### ISSUE THREAD

**Issue by ghost** [wavezhang/k8s-csi-lvm#3]
when i try to move a pod to another node (forced by adding nodeSelector) i get this error. Appearently the lvm-volume is not allowed to be accessed by the other node.

**Comment by wavezhang** [comment]
this plugin is for local lvm, so i add node affinity to pv

**Comment by ghost** [comment]
okay. but why do you use the lvm-metadata cluster service then?

**Comment by wavezhang** [comment]
You mean lvmd？Because provisioner need to remove lvm remotely

btw. I‘m considering add support for clvm’

**Comment by ghost** [comment]
Ok, i understand. So node affinity is a show-stopper for me. 

Thank you kindly for your support though.
