### ISSUE TITLE
Attach node when pv is created/Support WaitForFirstConsumer

### ISSUE THREAD

**Issue by rmb938** [wavezhang/k8s-csi-lvm#4]
Hi, I started trying out this csi plugin on my cluster and it works great however I have a few questions.

Currently when a pvc is created a pv is instantly made but the lvm volume doesn't actually get created until a pod wants to mount it.

While is works perfectly fine I would like the available storage on the node to be taken into account while scheduling.

Is it possible to make it so when the pv is created it gets assigned to a node that has free space?

An alternative would be supporting `WaitForFirstConsumer` in the storage class.

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-lvm
provisioner: csi-lvmplugin
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

As documented here: https://kubernetes.io/docs/concepts/storage/storage-classes/#local
`Delaying volume binding allows the scheduler to consider all of a pod’s scheduling constraints when choosing an appropriate PersistentVolume for a PersistentVolumeClaim.`

**Comment by rmb938** [comment]
Err actaully I just read the csi spec and there doesn't really seem to be a way to attach a volume to a node. I may have to come up with a different way to consider storage while scheduling pods.


Unless you have any ideas on how to do it.

**Comment by wavezhang** [comment]
need a custom scheduler to do this
