### ISSUE TITLE
How to modify volume group name

### ISSUE THREAD

**Issue by yuchunyun** [wavezhang/k8s-csi-lvm#5]
I found volume group name "k8s" is fixed in controllerserver.go,When I modify it and BUILD agein, I get an error "*"k8s-csi-lvm/vendor/k8s.io/client-go/kubernetes".Clientset does not implement "k8s-csi-lvm/vendor/github.com/wavezhang/k8s-csi-lvm/vendor/k8s.io/client-go/kubernetes".Interface (wrong type for Admissionregistration method)".Please tell me how to solve it

**Comment by wavezhang** [comment]
I've update code to support change volume group name by specify `--vgName` param in driver container

**Comment by yuchunyun** [comment]
Thank you. It does work.
But it still doesn't seem to support version v1.0.2 of the external container（attacher、provisioner、csi-node-driver-registrar） for k8s。
The error is as follows：
connection.go:141] GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v1.Identity
main.go:128] rpc error: code = Unimplemented desc = unknown service csi.v1.Identity

**Comment by wavezhang** [comment]
This project now do not support CSI v1，you can try use yamls in /deploy/kubernetes-1.12

**Comment by yuchunyun** [comment]
It can be used to, but I also encountered a problem. I have three storage nodes (A, B, C) to provide VG and have been used for part of the VG，If there is only one node (C) of the remaining space can satisfy the need of new POD storage resources, and then the problem is here，The POD is not necessarily will be automatically scheduled to the node (C), when it is scheduled to C outside of the node will be an error.Is there any way to solve？

**Comment by WMP** [comment]
We use this plugin on storage matrix. In storage matrix LUN we have 1TB PV, and this LUN is connected over SAN to all k8s nodes. On this PV is created one VG with locking, and all nodes create LVs on this VG.

**Comment by wavezhang** [comment]
@yuchunyun @WMP Please Open new Issue
