### ISSUE TITLE
instruction #2 should be updated to specify that node.sh should be executed from 'deploy' directory

### ISSUE THREAD

**Issue by vadbluedata** [wavezhang/k8s-csi-lvm#7]
should say:
> cd deploy
> ./node.sh

otherwise, lvmd will not be started correctly.

**Comment by wavezhang** [comment]
I've update install scripts to make it strongger. see https://github.com/wavezhang/k8s-csi-lvm/commit/a64133d1baed3a81ed261d4607f32a69fc9434fe
